version: '2'
services:
    api:
        container_name: api
        restart: always
        build: ./api
        ports:
            - '4000:4000'
        links:
            - mongo
        environment:
            - NODE_ENV=development
            - JWT_KEY=LookAtMeImASecret
            - MONGO_URI=mongodb://mongo:27017/graphql-start
            - MONGO_NAME=graphql-start
        command: yarn start:watch
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - '27017:27017'
    web:
        container_name: web
        build: ./web
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
            - REACT_APP_API_URI=http://localhost:4000/
        command: yarn start
